#!/usr/bin/env python3
"""
Phase5 Stage 2: Load comment analysis results into videos.comment_analysis [Qwen Cloud migration version]

Read comment_analysis_<timestamp>.json produced by stage 1 (3_analyze_comments.py),
and add the comment_analysis field to each document in the videos collection of the
qwen-soccertube DB using $set. Existing fields such as embedding and metadata are not touched.

Videos judged as is_soccer_related == false are treated as videos unrelated to soccer
(for example, cricket/basketball/volleyball videos accidentally matched by search.list
queries containing "World Cup") and are completely deleted from the videos collection
instead of being updated with $set. Analysis results that do not have an is_soccer_related
field (generated by older versions of 3_analyze_comments.py) are handled as before and
are not deleted for backward compatibility.

[Second half of the two-stage flow] This does not call the Gemini API. Matching is by video_id,
so the operation is idempotent.

[Date-based I/O]
  Input: ./data/<date>/comment_analysis_*.json (only outputs from our own
  3_analyze_comments.py are used; ../../soccer/ is not referenced)
  If <date> is omitted, today's date (YYYYMMDD) is used. For backfills, pass it as an argument
  (example: python 4_load_comment_analysis.py 20260704).

[Changes from the Gemini version]
  archive_run_files() from the Gemini version, which moved intermediate files under
  ../../soccer/data/ in the Gemini flow itself, was removed. Because the policy is not
  to touch the data pipeline (Gemini flow), the qwen_soccer side simply places files it
  generates under ./data/<date>/ from the beginning, so the archive/move process is no longer needed.

Prerequisites:
    pip install "pymongo[srv]"
    export MONGODB_URI='mongodb+srv://<user>:<password>@xxxx.mongodb.net/'
    export SOCCER_DB_NAME='qwen-soccertube'   # Keep this as-is if it is already set in .env

Run:
    python 4_load_comment_analysis.py [YYYYMMDD]
    (when omitted, it reads ./data/<today>/ using today's date)
"""

import os
import sys
import glob
import json
import argparse
from datetime import datetime, timezone

from pymongo import MongoClient, UpdateOne, DeleteOne
from pymongo.server_api import ServerApi
from pymongo.errors import ConnectionFailure, OperationFailure, ConfigurationError, BulkWriteError

from dotenv import load_dotenv
from pathlib import Path
SCRIPT_DIR = Path(__file__).parent
load_dotenv(SCRIPT_DIR / '.env')

# The default DB for the Qwen migration version is qwen-soccertube (separate from Gemini production soccertube).
DB_NAME = os.environ.get("SOCCER_DB_NAME", "qwen-soccertube")
COLL_NAME = os.environ.get("SOCCER_COLL_NAME", "videos")


def resolve_dirs(date_str: str) -> Path:
    """Resolve the I/O directory (qwen_soccer side, only our own outputs) from a date string."""
    return (SCRIPT_DIR / "data" / date_str).resolve()


def find_input_path(date_dir: Path) -> str:
    hits = sorted(glob.glob(str(date_dir / "comment_analysis_*.json")))
    if not hits:
        print(f"ERROR: {date_dir}/comment_analysis_*.json was not found.", file=sys.stderr)
        print("Run 3_analyze_comments.py for that date first.", file=sys.stderr)
        sys.exit(1)
    return hits[-1]


def main() -> int:
    parser = argparse.ArgumentParser(description="Phase5 Stage 2: Load comment analysis results (Qwen version)")
    parser.add_argument("date", nargs="?", default=None,
                         help="Target date (YYYYMMDD). Defaults to today if omitted")
    args = parser.parse_args()

    uri = os.environ.get("MONGODB_URI")
    if not uri:
        print("ERROR: MONGODB_URI is not set.", file=sys.stderr)
        return 1

    date_str = args.date or datetime.now().strftime("%Y%m%d")
    date_dir = resolve_dirs(date_str)

    path = find_input_path(date_dir)
    print(f"Target date: {date_str} / DB: {DB_NAME}")
    print(f"Input file: {path}")
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    analyses = data.get("analyses", {})
    if not analyses:
        print("ERROR: analyses is empty.", file=sys.stderr)
        return 1
    print(f"Load target: {len(analyses)} analysis results")

    try:
        mclient = MongoClient(uri, server_api=ServerApi("1"), serverSelectionTimeoutMS=5000)
        mclient.admin.command("ping")
    except (ConnectionFailure, OperationFailure, ConfigurationError) as e:
        print(f"ERROR: MongoDB connection failed: {e}", file=sys.stderr)
        return 1
    coll = mclient[DB_NAME][COLL_NAME]

    # Set comment_analysis on the matching document by video_id.
    # Delete videos from the videos collection when is_soccer_related == False.
    # Analysis results in the old format without this field are still treated as updates and not deleted
    # for backward compatibility.
    to_update = {}
    to_delete_ids = []
    for vid, analysis in analyses.items():
        is_soccer_related = analysis.get("is_soccer_related")
        if is_soccer_related is False:
            to_delete_ids.append(vid)
        else:
            to_update[vid] = analysis

    print(f"\nBreakdown: update targets={len(to_update)} / "
          f"delete targets as non-soccer videos={len(to_delete_ids)}")
    if to_delete_ids:
        print("  video_id values to delete: " + ", ".join(to_delete_ids))

    now = datetime.now(timezone.utc)

    if to_update:
        print("\nUpdating videos.comment_analysis ($set, matched by video_id)...")
        ops = [
            UpdateOne(
                {"video_id": vid},
                {"$set": {"comment_analysis": analysis, "last_analyzed": now}},
            )
            for vid, analysis in to_update.items()
        ]
        try:
            res = coll.bulk_write(ops, ordered=False)
        except BulkWriteError as e:
            print(f"ERROR: Problem during bulk update: {e.details}", file=sys.stderr)
            return 1

        matched = res.matched_count
        modified = res.modified_count
        print(f"  matched={matched}, modified={modified}")

        # Identify video_ids that did not match any document in videos (normally this should be 0).
        if matched < len(to_update):
            existing_ids = set(coll.distinct("video_id"))
            unmatched = [vid for vid in to_update if vid not in existing_ids]
            print(f"  WARNING: {len(unmatched)} video_id values did not match any document in videos: {unmatched}",
                  file=sys.stderr)
    else:
        print("\nNo update targets; skipping $set.")

    if to_delete_ids:
        print("\nDeleting non-soccer videos from the videos collection...")
        delete_ops = [DeleteOne({"video_id": vid}) for vid in to_delete_ids]
        try:
            del_res = coll.bulk_write(delete_ops, ordered=False)
        except BulkWriteError as e:
            print(f"ERROR: Problem during bulk delete: {e.details}", file=sys.stderr)
            return 1
        print(f"  deleted_count={del_res.deleted_count}")
        if del_res.deleted_count < len(to_delete_ids):
            print(f"  WARNING: {len(to_delete_ids)} delete targets but only "
                  f"{del_res.deleted_count} actually deleted (some may not have existed).", file=sys.stderr)

    # Verification: number of documents with comment_analysis.
    with_analysis = coll.count_documents({"comment_analysis": {"$exists": True}})
    total = coll.count_documents({})
    print(f"\nVerification: {with_analysis} documents with comment_analysis / {total} total documents")

    mclient.close()
    print(f"\nStage 2 complete. Added sentiment analysis results to {len(to_update)} videos and "
          f"deleted {len(to_delete_ids)} videos as non-soccer-related.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
